version: "3"
services: 
    redis:
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
          - ./db/redis.conf:/usr/local/etc/redis/redis.conf
        environment: 
            REDIS_HOST: redis
            REDIS_PORT: 6379
        ports: 
          - '6379:6379'